site_name: Giswater Documentation
theme:
  name: readthedocs
  logo: assets/giswater.png

extra_css:
  - assets/custom.css

nav:
  - Home: Markdownfiles/index.md
  - Introduction:
      - Overview: Markdownfiles/introduction/Introduction.md
  - Installation:
      - Work Rules: Markdownfiles/installation/Basic_work_rules.md
      - Necessary Software: Markdownfiles/installation/Necessary_software.md

plugins:
  - search