site_name: Giswater Documentation
theme:
  name: material
  logo: assets/giswater.png
font:
  text: Roboto
  code: Roboto Mono
nav:
  - Home: index.md
  - Introduction:
      - Overview: Markdownfiles/introduction/Introduction.md
  - Installation:
      - Work Rules: Markdownfiles/installation/Basic_work_rules.md
      - Necessary Software: Markdownfiles/installation/Necessary_software.md

plugins:
  - search