site_name: GISwater Documentation
theme:
  name: material
nav:
  - Home: index.md
  - 1. Introduction: 1_Introduction.md
  - 2. Necessary software: 2_Necessary_software.md
  - 3. Basic work rules: 3_Basic_work_rules.md
